Algoritmo "usuario diz inicio e fim da contagem"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
   inicioContagem, fimContagem, c: inteiro

Inicio
   escreva("inicio contagem: ")
   leia(inicioContagem)

   escreva("fim contagem: ")
   leia(fimContagem)

   para c de fimContagem ate passo inicioContagem 1 faca
      //repete 10x

      escreval(c)
   fimpara

Fimalgoritmo