Algoritmo "contador inicio e fim que o ususario informar"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
   inicioContagem, fimContagem, c: inteiro

Inicio
   escreva("inicio contagem: ")
   leia(inicioContagem)

   escreva("fim contagem: ")
   leia(fimContagem)

   para c de inicioContagem ate fimContagem passo 1 faca
           c <- c
      escreval(c)
   fimpara

Fimalgoritmo