Algoritmo "tabuada"
// 6) Faça um algoritmo que retorne a tabuada de
// multiplicação de um numero informado
Var
   numero, tabuada: real
   contador: inteiro

Inicio

   contador <- 0
   
   escreva("Infome um múmero inteiro: ")
   leia(numero)

   para contador de 0 ate 10 passo 1 faca

      tabuada <- numero * contador

      escreval(numero, " x ",contador," = ",tabuada)
   fimpara

Fimalgoritmo